export default {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
                    "outline": "#72787b",
                    "inverse-primary": "#abcbdb",
                    "primary-fixed-dim": "#abcbdb",
                    "on-secondary-container": "#795d65",
                    "outline-variant": "#c2c7cb",
                    "primary": "#065373",
                    "inverse-on-surface": "#f2f0f0",
                    "tertiary-container": "#d3d3d3",
                    "surface-container-lowest": "#ffffff",
                    "on-secondary": "#ffffff",
                    "surface-container-high": "#eae8e7",
                    "on-background": "#1b1c1c",
                    "on-primary": "#ffffff",
                    "surface-dim": "#dbd9d9",
                    "on-tertiary-fixed-variant": "#454747",
                    "on-error-container": "#93000a",
                    "primary-fixed": "#c7e7f8",
                    "on-primary-container": "#415f6c",
                    "on-surface": "#1b1c1c",
                    "on-primary-fixed": "#001f29",
                    "error": "#ba1a1a",
                    "surface-bright": "#fbf9f8",
                    "secondary-container": "#fed9e2",
                    "secondary": "#72575f",
                    "on-tertiary-container": "#595b5b",
                    "on-secondary-fixed": "#2a161c",
                    "secondary-fixed-dim": "#e0bec6",
                    "surface-container-low": "#f7d3d0",
                    "on-tertiary": "#ffffff",
                    "surface-container": "#efeded",
                    "on-primary-fixed-variant": "#2c4b58",
                    "surface-container-highest": "#e4e2e2",
                    "secondary-fixed": "#fed9e2",
                    "on-secondary-fixed-variant": "#594047",
                    "tertiary-fixed-dim": "#c6c6c7",
                    "error-container": "#ffdad6",
                    "on-tertiary-fixed": "#1a1c1c",
                    "on-surface-variant": "#42484b",
                    "background": "#fbf9f8",
                    "surface-variant": "#e4e2e2",
                    "tertiary-fixed": "#e2e2e2",
                    "tertiary": "#5d5f5f",
                    "inverse-surface": "#303030",
                    "on-error": "#ffffff",
                    "surface-tint": "#446370",
                    "primary-container": "#b8d8e8",
                    "surface": "#fbf9f8"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "container-max": "1200px",
                    "section-gap": "80px",
                    "gutter": "24px",
                    "margin-mobile": "16px",
                    "margin-desktop": "64px",
                    "unit": "8px"
            },
            "fontFamily": {
                    "display-lg-mobile": ["Playfair Display"],
                    "label-caps": ["DM Sans"],
                    "headline-sm": ["Playfair Display"],
                    "body-md": ["DM Sans"],
                    "display-lg": ["Playfair Display"],
                    "headline-md": ["Playfair Display"],
                    "body-lg": ["DM Sans"]
            },
            "fontSize": {
                    "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                    "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
                    "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
                    "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "display-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
            }
          },
    
  },
}